name: "Feature Request"
description: Create a new ticket for a new feature request
title: "[REQUEST] - <title>"
labels: [
  "enhancement"
]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the feature you are requesting.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please leave a description of the feature request here.
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: Potential Terraform Configuration
      description: Please provide an example of what the new resource or enhancement could look like in a Terraform config.
  - type: textarea
    id: references
    attributes:
      label: References
      description: |
        Information about referencing Github Issues: https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests

        Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Vendor blog posts or documentation? For example:

        * https://azure.microsoft.com/en-us/roadmap/virtual-network-service-endpoint-for-azure-cosmos-db/
